export const calendarMock = {
  suggestions: [
    {
      eventSq: 1,
      title: '주말 캠핑',
      startsAt: '2026-07-25 09:00',
      location: '가평',
      suggestion: '모기퇴치제, 아이스박스, 숯은 7/23까지 구매 권장',
    },
    {
      eventSq: 2,
      title: '반려묘 병원 방문',
      startsAt: '2026-07-28 15:30',
      location: '동네 동물병원',
      suggestion: '이동장 패드와 간식 재고 확인',
    },
    {
      eventSq: 3,
      title: '친구 생일',
      startsAt: '2026-08-02 19:00',
      location: '성수',
      suggestion: '선물 후보를 7/30 브리핑에 노출',
    },
    {
      eventSq: 4,
      title: '팀 회식',
      startsAt: '2026-08-05 19:30',
      location: '강남',
      suggestion: '숙취해소제와 간편식 재고를 8/4까지 확인',
    },
    {
      eventSq: 5,
      title: '가족 여행',
      startsAt: '2026-08-08 08:00',
      location: '제주',
      suggestion: '캐리어 정리용품, 여행용 세면도구는 8/6까지 구매 권장',
    },
    {
      eventSq: 6,
      title: '회사 워크숍',
      startsAt: '2026-08-12 10:00',
      location: '판교',
      suggestion: '노트, 보조배터리 재고를 8/10까지 확인',
    },
    {
      eventSq: 7,
      title: '아이 운동회',
      startsAt: '2026-08-15 09:30',
      location: '초등학교 운동장',
      suggestion: '물티슈, 쿨링스프레이, 간식은 8/13까지 준비',
    },
    {
      eventSq: 8,
      title: '집들이',
      startsAt: '2026-08-18 18:00',
      location: '마포',
      suggestion: '와인과 디저트 후보를 8/16 브리핑에 반영',
    },
    {
      eventSq: 9,
      title: '등산 동호회',
      startsAt: '2026-08-20 07:00',
      location: '북한산',
      suggestion: '등산양말, 에너지바, 이온음료는 8/18까지 구매 권장',
    },
    {
      eventSq: 10,
      title: '치과 정기검진',
      startsAt: '2026-08-22 14:00',
      location: '역삼 치과',
      suggestion: '구강청결제와 치실 재고를 검진 전에 확인',
    },
    {
      eventSq: 11,
      title: '부모님 방문',
      startsAt: '2026-08-24 11:00',
      location: '수원',
      suggestion: '과일 세트와 건강식품 후보를 8/22까지 정리',
    },
    {
      eventSq: 12,
      title: '비 오는 날 홈파티',
      startsAt: '2026-08-27 17:00',
      location: '집',
      suggestion: '간편요리 재료와 음료는 8/26까지 장보기',
    },
    {
      eventSq: 13,
      title: '캠핑 장비 점검',
      startsAt: '2026-08-29 16:00',
      location: '집',
      suggestion: '부탄가스, 랜턴 배터리 교체 여부를 8/28까지 확인',
    },
    {
      eventSq: 14,
      title: '월말 장보기',
      startsAt: '2026-08-31 10:00',
      location: '근처 마트',
      suggestion: '생필품·세제·휴지 대용량 구매 타이밍을 브리핑에 반영',
    },
  ],
};
